[platformio]
description = Induction Furnace Cooling Controller
src_dir = src
include_dir = include

; Общие настройки для всех сред
[common]
platform = espressif32
board = esp32-c6-devkitm-1
framework = espidf
monitor_speed = 115200

board_build.flash_size = 4MB
board_upload.flash_size = 4MB
board_build.flash_mode = dio
board_build.f_cpu = 160000000L

upload_port = COM3
upload_speed = 921600

; Флаги C++ (только для .cpp файлов)
build_flags_cpp = 
    -Wno-volatile
    -Wno-error=volatile

; Общие флаги для всех файлов
build_flags = 
    -DESP32C6
    -Wno-format-truncation
    -Wno-missing-field-initializers
    -fpermissive
    -Wno-error=missing-field-initializers

debug_build_flags = 
    -Og
    -ggdb3

[env:esp32-c6-devkitm-1]
extends = common

[env:production]
extends = common
build_type = release

build_flags = 
    ${common.build_flags}
    -DCONFIG_OPTIMIZATION_LEVEL_RELEASE=y
    -DCONFIG_OPTIMIZATION_ASSERTIONS_DISABLED=y
    -DCONFIG_LOG_DEFAULT_LEVEL=WARN
    -DCONFIG_LOG_MAXIMUM_LEVEL=4
    -DCONFIG_COMPILER_OPTIMIZATION_SIZE=y
    -DCONFIG_ESP_SYSTEM_PANIC_PRINT_HALT=y
    -DNDEBUG

[env:monitor]
extends = common
monitor_port = COM3
monitor_speed = 115200
monitor_filters = colorize,time